"""empty message

Revision ID: 26cd89284bf1
Revises: fdf85012f3a7
Create Date: 2023-10-29 17:16:24.431946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26cd89284bf1'
down_revision = 'fdf85012f3a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=800), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
