"""empty message

Revision ID: 288dd9dda5e9
Revises: 26cd89284bf1
Create Date: 2023-11-01 10:31:38.368250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288dd9dda5e9'
down_revision = '26cd89284bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component__image', schema=None) as batch_op:
        batch_op.drop_index('ix_component__image_component_id')
        batch_op.drop_index('ix_component__image_image_id')

    op.drop_table('component__image')
    with op.batch_alter_table('product__image', schema=None) as batch_op:
        batch_op.drop_index('ix_product__image_image_id')
        batch_op.drop_index('ix_product__image_product_id')

    op.drop_table('product__image')
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.SmallInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_component_image_id'), ['image_id'], unique=False)
        batch_op.create_foreign_key(None, 'image', ['image_id'], ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.SmallInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'image', ['image_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('image_id')

    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_component_image_id'))
        batch_op.drop_column('image_id')

    op.create_table('product__image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], name='product__image_image_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='product__image_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product__image_pkey')
    )
    with op.batch_alter_table('product__image', schema=None) as batch_op:
        batch_op.create_index('ix_product__image_product_id', ['product_id'], unique=False)
        batch_op.create_index('ix_product__image_image_id', ['image_id'], unique=False)

    op.create_table('component__image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('component_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], name='component__image_component_id_fkey'),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], name='component__image_image_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='component__image_pkey')
    )
    with op.batch_alter_table('component__image', schema=None) as batch_op:
        batch_op.create_index('ix_component__image_image_id', ['image_id'], unique=False)
        batch_op.create_index('ix_component__image_component_id', ['component_id'], unique=False)

    # ### end Alembic commands ###
