"""empty message

Revision ID: a16bc46876ef
Revises: ca7f8f443570
Create Date: 2023-11-06 13:33:05.654045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16bc46876ef'
down_revision = 'ca7f8f443570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_product_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('comment_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('comment_product_id_fkey', 'product', ['product_id'], ['id'])

    # ### end Alembic commands ###
