"""empty message

Revision ID: b9db44ba05f9
Revises: d36efec65dfb
Create Date: 2023-10-06 20:42:27.033467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9db44ba05f9'
down_revision = 'd36efec65dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_component_name'), ['name'], unique=True)

    op.create_table('component__image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('component__image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_component__image_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_component__image_image_id'), ['image_id'], unique=False)

    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_table('labor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_component_id'), ['component_id'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('labor_id', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=True)

    op.create_table('product__component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product__component', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product__component_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product__component_product_id'), ['product_id'], unique=False)

    op.create_table('product__image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product__image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product__image_image_id'), ['image_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product__image_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product__image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product__image_product_id'))
        batch_op.drop_index(batch_op.f('ix_product__image_image_id'))

    op.drop_table('product__image')
    with op.batch_alter_table('product__component', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product__component_product_id'))
        batch_op.drop_index(batch_op.f('ix_product__component_component_id'))

    op.drop_table('product__component')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_name'))

    op.drop_table('product')
    with op.batch_alter_table('price', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_component_id'))

    op.drop_table('price')
    op.drop_table('labor')
    op.drop_table('image')
    with op.batch_alter_table('component__image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_component__image_image_id'))
        batch_op.drop_index(batch_op.f('ix_component__image_component_id'))

    op.drop_table('component__image')
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_component_name'))

    op.drop_table('component')
    # ### end Alembic commands ###
