"""empty message

Revision ID: c2a1880a9d6c
Revises: b9db44ba05f9
Create Date: 2023-10-10 21:06:36.844148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a1880a9d6c'
down_revision = 'b9db44ba05f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_adress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('street', sa.String(length=120), nullable=True),
    sa.Column('home', sa.String(length=120), nullable=True),
    sa.Column('apartment', sa.String(length=120), nullable=True),
    sa.Column('submit', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_adress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_adress_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_adress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_adress_user_id'))

    op.drop_table('user_adress')
    # ### end Alembic commands ###
