"""empty message

Revision ID: fdf85012f3a7
Revises: 8727d8face8b
Create Date: 2023-10-27 18:29:12.512421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf85012f3a7'
down_revision = '8727d8face8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_user_id'), ['user_id'], unique=False)

    op.create_table('order_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_line_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_line_product_id'), ['product_id'], unique=False)

    op.create_table('line_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['order_line.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('line_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_status_line_id'), ['line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_status_status_id'), ['status_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_status_status_id'))
        batch_op.drop_index(batch_op.f('ix_line_status_line_id'))

    op.drop_table('line_status')
    with op.batch_alter_table('order_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_line_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_line_order_id'))

    op.drop_table('order_line')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_user_id'))

    op.drop_table('order')
    op.drop_table('status')
    # ### end Alembic commands ###
